version: 0.1.0.{build}

pull_requests:
  do_not_increment_build_number: true

branches:
  only:
    - master

skip_non_tags: false

image: Visual Studio 2015

shallow_clone: true

clone_depth: 1

clone_folder: C:\projects\devrider

environment:
  PFX_PASSWORD:
    secure: ND6GzCbQh+RsdxMPaXF+WA==
  APPVEYOR_SKIP_FINALIZE_ON_EXIT: false
  PYTHONUNBUFFERED: 1
  matrix:
    - PYTHON: C:\Python36-x64
      PYTHON_VERSION: 3.6.6
      PYTHON_ARCH: 64

install:
  # ---------------------------------------- 64-bit build ----------------------------------------

  - set PATH=%PYTHONHOME%;%PYTHONHOME%\scripts;%PYTHONHOME%\tools\scripts;%PATH%
  - cd C:\projects\devrider
  # Installing latest pip + setuptools + dependencies
  - "%PYTHON%\\python.exe -m pip install -U pip setuptools"
  - "%PYTHON%\\python.exe -m pip install -r requirements\\build.txt"
  - "%PYTHON%\\python.exe -m pip install -r requirements\\base.txt"
  # Setting up libmpv build subfolders...
  - mkdir "_build\pyinstaller\temp"
  # Setup build environment for MSVC++
  - call "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64
  # Freezing w/ PyInstaller
  - cd _build/pyinstaller
  - call build.pyinstaller.win.bat 64 %PFX_PASSWORD%
  - cd ..\InnoSetup\Output
  - appveyor PushArtifact DevRider-0.1.0-setup-win64.exe
  - appveyor exit

nuget:
  disable_publish_on_pr: true

test: off